**Problem 1**
Clean up the file. This means getting rid of duplicates; you can assume that no student can register for the same course more than once. How many duplicate records do you find? Some of the fields have bad or missing values; repair those that you can (and explain what a repair means).

In [2]:
import pandas as pd
import csv
import sys

Opening the data: Because of the number of corrupted lines/entries in the data, it was impossible to open the data as a full file by reading it into a pandas dataframe or even by reading it in line by line. The code below tries to read each line, and appends only the lines that are open-able to a list, good_lines. We count the number of bad lines

In [15]:
# Note - change file path or put csv in your directory to run this code yourself
with open('/Users/amydanoff/Desktop/APCOMP221/dirty_sample_small.csv') as f:
    length = 661486
    good_lines = []
    bad_lines = 0
    for i in range(length):
        try:
            value = f.readline()
            good_lines.append(value)
        except:
            bad_lines += 1
    print("This file has", bad_lines, "unreadable lines")

This file has 2337 unreadable lines

In [16]:
print("We are left with", len(good_lines), "readable lines.")

We are left with 659149 readable lines.

Read in header to figure out which categories we are supposed to have in our dataframe.

In [17]:
# Create header dataframe from header csv
header = pd.DataFrame.from_csv('dirty_sample_small_header.csv')
header.loc[-1] = ['course_id']
header.index = header.index + 1
header = header.sort_index()
header = header.transpose()
header

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ipykernel_launcher.py:2: FutureWarning: from_csv is deprecated. Please use read_csv(...) instead. Note that some of the default arguments are different, so please refer to the documentation for from_csv when changing your function calls

FileNotFoundError: File b'dirty_sample_small_header.csv' does not exist

In [18]:
good_lines[:2]

['_Nations,,Latin America and the Caribbean,-23.4507,-46.5262,m,1980,m,,0.7,4/24/18 23:35,35:15.4,35:41.9,9,1,0,1,,,,,,,Student,0,0,0,audit,1,,,,\n',
 'HarvardX/PH525.1x/1T2018,28454,TRUE,FALSE,FALSE,FALSE,177.18.230.216,BR,Brazil,Americas,Guarulhos,SP,Sao Paulo,,South America,Developing_Nations,,Latin America and the Caribbean,-23.4507,-46.5262,m,1980,m,,0.7,4/24/18 23:35,35:15.4,35:41.9,9,1,0,1,,,,,,,Student,0,0,0,audit,1,,,,\n']

In [19]:
df = pd.DataFrame([sub.split(",") for sub in good_lines])

In [20]:
# TEST - ensure that dataframe works
print(len(df))

659149

In [21]:
df.head()

,0,1,2,3,4,5,6,7,8,9,...,38,39,40,41,42,43,44,45,46,47
0,_Nations,,Latin America and the Caribbean,-23.4507,-46.5262,m,1980,m,,0.7,...,None,None,None,None,None,None,None,None,None,None
1,HarvardX/PH525.1x/1T2018,28454,TRUE,FALSE,FALSE,FALSE,177.18.230.216,BR,Brazil,Americas,...,Student,0,0,0,audit,1,,,,\n
2,HarvardX/PH525.1x/1T2018,28454,TRUE,FALSE,FALSE,FALSE,177.18.230.216,BR,Brazil,Americas,...,Student,0,0,0,audit,1,,,,\n
3,HarvardX/PH525.1x/1T2018,28454,TRUE,FALSE,FALSE,FALSE,177.18.230.216,BR,Brazil,Americas,...,Student,0,0,0,audit,1,,,,\n
4,HarvardX/PH525.1x/1T2018,43100,FALSE,,FALSE,FALSE,213.249.56.36,GR,Greece,Europe,...,Student,0,0,0,audit,1,,,,\n

In [22]:
df.drop([0])

,0,1,2,3,4,5,6,7,8,9,...,38,39,40,41,42,43,44,45,46,47
1,HarvardX/PH525.1x/1T2018,28454,TRUE,FALSE,FALSE,FALSE,177.18.230.216,BR,Brazil,Americas,...,Student,0,0,0,audit,1,,,,\n
2,HarvardX/PH525.1x/1T2018,28454,TRUE,FALSE,FALSE,FALSE,177.18.230.216,BR,Brazil,Americas,...,Student,0,0,0,audit,1,,,,\n
3,HarvardX/PH525.1x/1T2018,28454,TRUE,FALSE,FALSE,FALSE,177.18.230.216,BR,Brazil,Americas,...,Student,0,0,0,audit,1,,,,\n
4,HarvardX/PH525.1x/1T2018,43100,FALSE,,FALSE,FALSE,213.249.56.36,GR,Greece,Europe,...,Student,0,0,0,audit,1,,,,\n
5,HarvardX/PH525.1x/1T2018,43100,FALSE,,FALSE,FALSE,213.249.56.36,GR,Greece,Europe,...,Student,0,0,0,audit,1,,,,\n
6,HarvardX/PH525.1x/1T2018,43100,FALSE,,FALSE,FALSE,213.249.56.36,GR,Greece,Europe,...,Student,0,0,0,audit,1,,,,\n
7,HarvardX/PH525.1x/1T2018,43100,FALSE,,FALSE,FALSE,213.249.56.36,GR,Greece,Europe,...,Student,0,0,0,audit,1,,,,\n
8,HarvardX/PH525.1x/1T2018,43100,FALSE,,FALSE,FALSE,213.249.56.36,GR,Greece,Europe,...,Student,0,0,0,audit,1,,,,\n
9,HarvardX/PH525.1x/1T2018,43100,FALSE,,FALSE,FALSE,213.249.56.36,GR,Greece,Europe,...,Student,0,0,0,audit,1,,,,\n
10,HarvardX/PH525.1x/1T2018,43100,FALSE,,FALSE,FALSE,213.249.56.36,GR,Greece,Europe,...,Student,0,0,0,audit,1,,,,\n
11,HarvardX/PH525.1x/1T2018,43100,FALSE,,FALSE,FALSE,213.249.56.36,GR,Greece,Europe,...,Student,0,0,0,audit,1,,,,\n
12,HarvardX/PH525.1x/1T2018,44413,FALSE,,FALSE,FALSE,95.91.213.204,DE,Germany,Europe,...,Student,0,0,0,audit,1,,,,\n
13,HarvardX/PH525.1x/1T2018,44413,FALSE,,FALSE,FALSE,95.91.213.204,DE,Germany,Europe,...,Student,0,0,0,audit,1,,,,\n
14,HarvardX/PH525.1x/1T2018,44413,FALSE,,FALSE,FALSE,95.91.213.204,DE,Germany,Europe,...,Student,0,0,0,audit,1,,,,\n
15,HarvardX/PH525.1x/1T2018,44413,FALSE,,FALSE,FALSE,95.91.213.204,DE,Germany,Europe,...,Student,0,0,0,audit,1,,,,\n
16,HarvardX/PH525.1x/1T2018,44413,FALSE,,FALSE,FALSE,95.91.213.204,DE,Germany,Europe,...,Student,0,0,0,audit,1,,,,\n
17,HarvardX/PH525.1x/1T2018,44413,FALSE,,FALSE,FALSE,95.91.213.204,DE,Germany,Europe,...,Student,0,0,0,audit,1,,,,\n
18,HarvardX/PH525.1x/1T2018,44413,FALSE,,FALSE,FALSE,95.91.213.204,DE,Germany,Europe,...,Student,0,0,0,audit,1,,,,\n
19,HarvardX/PH525.1x/1T2018,44413,FALSE,,FALSE,FALSE,95.91.213.204,DE,Germany,Europe,...,Student,0,0,0,audit,1,,,,\n
20,HarvardX/PH525.1x/1T2018,44413,FALSE,,FALSE,FALSE,95.91.213.204,DE,Germany,Europe,...,Student,0,0,0,audit,1,,,,\n
21,HarvardX/PH525.1x/1T2018,44413,FALSE,,FALSE,FALSE,95.91.213.204,DE,Germany,Europe,...,Student,0,0,0,audit,1,,,,\n
22,HarvardX/PH525.1x/1T2018,44413,FALSE,,FALSE,FALSE,95.91.213.204,DE,Germany,Europe,...,Student,0,0,0,audit,1,,,,\n
23,HarvardX/PH525.1x/1T2018,44413,FALSE,,FALSE,FALSE,95.91.213.204,DE,Germany,Europe,...,Student,0,0,0,audit,1,,,,\n
24,HarvardX/PH525.1x/1T2018,44413,FALSE,,FALSE,FALSE,95.91.213.204,DE,Germany,Europe,...,Student,0,0,0,audit,1,,,,\n
25,HarvardX/PH525.1x/1T2018,44413,FALSE,,FALSE,FALSE,95.91.213.204,DE,Germany,Europe,...,Student,0,0,0,audit,1,,,,\n
26,HarvardX/PH525.1x/1T2018,44413,FALSE,,FALSE,FALSE,95.91.213.204,DE,Germany,Europe,...,Student,0,0,0,audit,1,,,,\n
27,HarvardX/PH525.1x/1T2018,44413,FALSE,,FALSE,FALSE,95.91.213.204,DE,Germany,Europe,...,Student,0,0,0,audit,1,,,,\n
28,HarvardX/PH525.1x/1T2018,44413,FALSE,,FALSE,FALSE,95.91.213.204,DE,Germany,Europe,...,Student,0,0,0,audit,1,,,,\n
29,HarvardX/PH525.1x/1T2018,44413,FALSE,,FALSE,FALSE,95.91.213.204,DE,Germany,Europe,...,Student,0,0,0,audit,1,,,,\n
30,HarvardX/PH525.1x/1T2018,44413,FALSE,,FALSE,FALSE,95.91.213.204,DE,Germany,Europe,...,Student,0,0,0,audit,1,,,,\n
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
659119,,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
659120,,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
659121,,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
659122,,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
659123,,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
659124,,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
659125,,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
659126,,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
659127,,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
659128,,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
659129,,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
659130,,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
659131,,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
659132,,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
659133,,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
659134,,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
659135,,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
659136,,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
659137,,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
659138,,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
659139,,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
659140,,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
659141,,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
659142,,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
659143,,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
659144,,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
659145,,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
659146,,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
659147,,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
659148,,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None

In [23]:
my_header = header.iloc[0].reset_index()['course_id']
my_header

NameError: name 'header' is not defined

In [ ]:
# Set header dataframe as header of main dataframe
df = df.rename(columns=my_header)

In [ ]:
df.head()

In [ ]:
df.drop([0])

**Removing Duplicate Records** Now that we have loaded our data into a workable dataframe, we can begin our analysis. We first look for duplicates within the 'user_id' column, a column that should have all unique values, to determine how many duplicate students we have in our dataframe (and thus need to remove).

In [ ]:
# Find number of unique records in user_id column
unique_entries = df['user_id'].unique()
print("This dataset has", len(unique_entries), "unique entries")
print("Thus, we have", len(df) - len(unique_entries), "duplicate entries")

In [ ]:
# Create data frame with only unique entries (based on user id)
unique_df = df.drop_duplicates(subset='user_id')

In [ ]:
print(len(unique_df))

**Filling Missing Values** With our new dataframe (where non-unique rows have been dropped), we fill all missing values using a statistically representative draw from that column

In [ ]:
import numpy as np

In [ ]:
# Import methods written for reidentification pset